- name: Update Interface Configuration
  template: src=ifcfg.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-{{ interface }}
  notify: Restart Networking
  tags:
    - network

- name: Install Bridge Configuration
  copy: src=ifcfg-br0
        dest=/etc/sysconfig/network-scripts/
  notify: Restart Networking
  tags:
    - network

