- name: Check Interface Configuration
  shell: grep -q dhcp /etc/sysconfig/network-scripts/ifcfg-{{ interface }} && echo -n "dhcp" || echo -n "static"
  register: dhcp_check
  ignore_errors: yes
  tags:
    - network

- name: Update DHCP Interface Configuration
  template: src=ifcfg-dhcp.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-{{ interface }}
  when: dhcp_check.stdout == "dhcp"
  notify: Restart Networking
  tags:
    - network

- name: Update Static Interface Configuration
  template: src=ifcfg-static.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-{{ interface }}
  when: dhcp_check.stdout == "static"
  notify: Restart Networking
  tags:
    - network

- name: Install Bridge Configuration
  template: src=ifcfg-br0.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-br0
  notify: Restart Networking
  tags:
    - network

