---
- name: Disable IPTables
  service: name=iptables state=stopped enabled=false
  tags:
    - preconfig

- name: Remove IPTables Rules
  command: rm -f /etc/sysconfig/iptables removes=/etc/sysconfig/iptables
  tags:
    - preconfig

