---
- name: Common Machine Configuration
  hosts: all
  vars_files:
    - cloud_config.yml
  roles:
    - common

- name: Node Controller Installation
  hosts: node_controller
  roles:
    - node_controller

- name: Cloud Controller Installation
  hosts: cloud_controller
  roles:
    - cloud_controller

- name: Cluster Controller Installation
  hosts: cluster_controller
  roles:
    - cluster_controller

- name: Storage Controller Installation
  hosts: storage_controller
  roles:
    - storage_controller

- name: Walrus Installation
  hosts: walrus
  roles:
    - walrus

