---
- name: Install Cloud Controller Runtime Dependencies
  yum: name=postgresql91-server,python-boto state=latest

- name: Install Cloud Controller Symlink
  file: src={{ eucalyptus_prefix }}/etc/init.d/eucalyptus-cloud
        dest=/etc/init.d/eucalyptus-cloud
        state=link
