- name: Configure Eucalyptus Source
  shell: chdir={{ eucalyptus_source_dir }}
         executable=/bin/bash
         {{ configure_cmd }}
  environment:
    EUCALYPTUS: '{{ eucalyptus_prefix }}'
  tags:
    - source

- name: Build Eucalyptus Source
  shell: chdir={{ eucalyptus_source_dir }}
         executable=/bin/bash
         make -j8
  environment:
    EUCALYPTUS: '{{ eucalyptus_prefix }}'
  tags:
    - source

- name: Install Eucalyptus Source
  shell: chdir={{ eucalyptus_source_dir }}
         executable=/bin/bash
         make install
  environment:
    EUCALYPTUS: '{{ eucalyptus_prefix }}'
  tags:
    - source
