---
- name: Install Development Repository
  template: src=eucalyptus-devel.repo.j2
            dest=/etc/yum.repos.d/eucalyptus-devel.repo

- include: vddk.yml
  when: install_enterprise == true

- name: Install Yum Utils
  yum: name=yum-utils state=present

- name: Install Build Dependencies
  shell: yum-builddep {{ srpm_url }}
  tags:
    - deps

- name: Install SSH Configuration
  copy: src=ssh_config dest=~/.ssh/config

- name: Checkout Internal Eucalyptus Repository
  git: dest="{{ eucalyptus_source_dir }}"
       repo="{{ eucalyptus_internal_repo }}"
       version="{{ enterprise_commit_ref }}"
  when: install_enterprise == true

- name: Checkout Github Eucalyptus Repository
  git: dest="{{ eucalyptus_source_dir }}"
       repo="{{ eucalyptus_github_repo }}"
       version="{{ eucalyptus_commit_ref }}"
  when: install_enterprise == false

- name: Download WSDL Script
  get_url: url=https://raw.github.com/eucalyptus/eucalyptus-rpmspec/master/euca-WSDL2C.sh
           dest=/opt/euca-WSDL2C.sh
