---
- name: Install Walrus
  hosts: walrus
  vars_files:
    - ../vars/cloud_defaults.yml
    - ../vars/source.yml
    - ['../../cloud_config.yml']
  tasks:
    - name: Install Walrus Symlink
      file: src={{ eucalyptus_prefix }}/etc/init.d/eucalyptus-cloud
            dst=/etc/init.d/eucalyptus-cloud
            state=link
