---
- name: Install Cluster Controller Runtime Dependencies
  yum: name=httpd,python-boto state=latest

- name: Install Cluster Controller Symlink
  file: src={{ eucalyptus_prefix }}/etc/init.d/eucalyptus-cc
        dest=/etc/init.d/eucalyptus-cc
        state=link
