---
- name: EMC SAN Install
  yum: name=eucalyptus-enterprise-storage-san-emc state=latest 
  when: san_provider == 'EmcVnxProvider'
  tags:
    - packages

- name: Equallogic SAN Install
  yum: name=eucalyptus-enterprise-storage-san-equallogic state=latest
  when: san_provider == 'EquallogicProvider'
  tags:
    - packages

- name: NetApp SAN Install
  yum: name=eucalyptus-enterprise-storage-san-netapp state=latest
  when: san_provider == 'NetappProvider'
  tags:
    - packages
