---
- name: Install Cloud Controller
  hosts: cloud_controller
  vars_files:
    - ['../../cloud_config.yml', '../../vars/cloud_defaults.yml']
  tasks:
    - name: Cloud Package Install
      yum: pkg=eucalyptus-cloud state=present
      tags:
        - packages
    - include: clc_enterprise.yml
      when: install_enterprise == true
