---
- name: Install Storage Controller
  hosts: storage_controller
  vars_files:
    - ['../../cloud_config.yml', '../../vars/cloud_defaults.yml']
  tasks:
    - name: Storage Package Install 
      yum: pkg=eucalyptus-sc state=present
      tags:
        - packages
    - include: sc_enterprise.yml
      when: install_enterprise == true
