---
- name: Install Node Controller Runtime Dependencies
  yum: name=httpd,python-boto state=latest

- name: Install Node Controller Symlink
  file: src={{ eucalyptus_prefix }}/etc/init.d/eucalyptus-nc
        dest=/etc/init.d/eucalyptus-nc
        state=link
