---
- name: Common Host Configuration
  hosts: all
  vars_files:
    - vars/cloud_defaults.yml
    - ['../cloud_config.yml']
  roles:
    - common

- name: Install Repositories
  hosts: all
  vars_files:
    - vars/cloud_defaults.yml
    - ['../cloud_config.yml']
  tasks:
    - include: tasks/repositories.yml

- include: package/euca2ools.yml
- include: package/console.yml
- include: package/clc.yml
- include: package/cc.yml
- include: package/sc.yml
- include: package/walrus.yml
- include: package/nc.yml

