---
- name: Common Host Configuration
  hosts: all
  vars_files:
    - vars/cloud_defaults.yml
    - ['../cloud_config.yml']
  roles:
    - common
    - euca2ools
    - source_common

- name: Cloud Controller Configuration
  hosts: cloud_controller
  vars_files:
    - vars/cloud_defaults.yml
    - ['../cloud_config.yml']
  roles:
    - clc_source

- name: Walrus Configuration
  hosts: walrus
  vars_files:
    - vars/cloud_defaults.yml
    - ['../cloud_config.yml']
  roles:
    - walrus_common
    - walrus_source

- name: Storage Controller Configuration
  hosts: storage_controller
  vars_files:
    - vars/cloud_defaults.yml
    - ['../cloud_config.yml']
  roles:
    - sc_source

- name: Cluster Controller Configuration
  hosts: cluster_controller
  vars_files:
    - vars/cloud_defaults.yml
    - ['../cloud_config.yml']
  roles:
    - cc_source

- name: Node Controller Configuration
  hosts: node_controller
  vars_files:
    - vars/cloud_defaults.yml
    - ['../cloud_config.yml']
  roles:
    - nc_source
