---
- name: Common Host Configuration
  hosts: all
  vars_files:
    - ['../cloud_config.yml', '../vars/cloud_defaults.yml']
  roles:
    - common

- name: Prepare Source
  hosts: all
  vars_files:
    - ../cloud_config.yml
    - vars/source.yml
  tasks:
    - include: tasks/deps.yml
    - name: Clean Prior to Build
      shell: chdir={{ eucalyptus_source_dir }}
             executable=/bin/bash
             make distclean
      environment:
        EUCALYPTUS: '{{ eucalyptus_prefix }}'
    - include: tasks/build.yml
