---
- name: Common Host Configuration
  hosts: all
  vars_files:
    - vars/cloud_defaults.yml
    - ['../cloud_config.yml']
  roles:
    - common

- include: packages/euca2ools.yml

- name: Prepare Source
  hosts: all
  vars_files:
    - vars/cloud_defaults.yml
    - vars/source.yml
    - ['../cloud_config.yml']
  tasks:
    - include: tasks/deps.yml
    - include: tasks/build.yml
