---
- name: Common Host Configuration
  hosts: all
  vars_files:
    - ['../cloud_config.yml', '../vars/cloud_defaults.yml']
  roles:
    - common

- name: Prepare Source
  hosts: all
  vars_files:
    - ../cloud_config.yml
    - vars/source.yml
  tasks:
    - name: Install Development Repository
      template: src=templates/eucalyptus-devel.repo.j2
                dest=/etc/yum.repos.d/eucalyptus-devel.repo

    - name: Install Build Dependencies
      yum: pkg={{ devel_packages|join(',') }} state=installed

    - name: Checkout Eucalyptus Repository
      git: dest={{ eucalyptus_source_dir }}
           repo={{ eucalyptus_repo }}
           version={{ enterprise_commit_ref }}

    - name: Configure Eucalyptus Source
      shell: chdir={{ eucalyptus_source_dir }}
             executable=/bin/bash
             {{ configure_cmd }}
      environment:
        EUCALYPTUS: '{{ eucalyptus_prefix }}'
      tags:
        - source_build

    - name: Build Eucalyptus Source
      shell: chdir={{ eucalyptus_source_dir }}
             executable=/bin/bash
             make -j8
      environment:
        EUCALYPTUS: '{{ eucalyptus_prefix }}'
      tags:
        - source_build

    - name: Install Eucalyptus Source
      shell: chdir={{ eucalyptus_source_dir }}
             executable=/bin/bash
             make deploy
      environment:
        EUCALYPTUS: '{{ eucalyptus_prefix }}'
      tags:
        - source_build

