---
- name: Common Host Configuration
  hosts: all
  vars_files:
    - vars/cloud_defaults.yml
    - ['../cloud_config.yml']
  roles:
    - common

- include: package/euca2ools.yml

- name: Source Install
  hosts: all
  vars_files:
    - vars/cloud_defaults.yml
    - vars/source.yml
    - ['../cloud_config.yml']
  tasks:
    - include: tasks/repositories.yml
    - include: tasks/deps.yml
    - include: tasks/build.yml
    - name: Create Eucalyptus User
      user: name=eucalyptus

- include: source/clc.yml
- include: source/walrus.yml
- include: source/sc.yml
- include: source/cc.yml
- include: source/nc.yml

